### ISSUE TITLE
Could not create H2 JDBC Connection Pool via admin UI

### ISSUE THREAD

**Issue by afrunt** [payara/Payara#2149]
# Description #
----------

## Expected Outcome

Pool should be created. Additional issue is with saving of empty password, that is impossible via UI (only via changing of domain.xml)

## Current Outcome

Exception

[#|2017-11-11T22:15:34.058+0200|SEVERE|Payara 5.0.Alpha3|org.glassfish.admingui|_ThreadID=52;_ThreadName=admin-thread-pool::admin-listener(1);_TimeMillis=1510431334058;_LevelValue=1000;|
  RestResponse.getResponse() gives FAILURE.  endpoint = 'http://localhost:4848/management/domain/resources/flush-connection-pool.json'; attrs = '{id=jdbc/corePool}'|#]

[#|2017-11-11T22:34:07.276+0200|SEVERE|Payara 5.0.Alpha3|javax.enterprise.admin.rest.client|_ThreadID=121;_ThreadName=admin-thread-pool::admin-listener(5);_TimeMillis=1510432447276;_LevelValue=1000;_MessageID=NCLS-RSCL-00004;|
  An error occurred while processing a JSON object.
javax.json.stream.JsonParsingException: Unexpected char 58 at (line no=1, column no=146, offset=145)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:601)
	at org.glassfish.json.JsonTokenizer.unescape(JsonTokenizer.java:231)
	at org.glassfish.json.JsonTokenizer.readString(JsonTokenizer.java:184)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:379)
	at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:459)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:363)
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:338)
	at org.glassfish.json.JsonParserImpl.getValue(JsonParserImpl.java:182)
	at org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:326)
	at org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:164)
	at org.glassfish.admin.rest.client.utils.MarshallingUtils.getPropertiesFromJson(MarshallingUtils.java:85)
	at org.glassfish.admin.rest.readers.JsonPropertyListReader.readFrom(JsonPropertyListReader.java:88)
	at org.glassfish.admin.rest.readers.JsonPropertyListReader.readFrom(JsonPropertyListReader.java:66)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:73)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1091)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:271)
	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:97)
	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:80)
	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:74)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:92)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:133)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:243)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
	at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:318)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:180)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:483)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:242)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
|#]

[#|2017-11-11T22:34:07.281+0200|SEVERE|Payara 5.0.Alpha3|org.glassfish.admingui|_ThreadID=119;_ThreadName=admin-thread-pool::admin-listener(3);_TimeMillis=1510432447281;_LevelValue=1000;|
  RestResponse.getResponse() gives FAILURE.  endpoint = 'http://localhost:4848/management/domain/resources/jdbc-connection-pool/jdbc%2FcorePool/property.json'; attrs = '[{"name":"User","description":"","value":"SA"},{"name":"LoginTimeout","description":"","value":"0"},{"name":"URL","description":"","value":"jdbc\:h2\:~\/test;AUTO_SERVER=TRUE"},{"name":"Url","description":"","value":"jdbc\:h2\:~\/test;AUTO_SERVER=TRUE"}]'|#]

## Steps to reproduce (Only for bug reports) 

1. Run H2 server java -cp h2-1.4.196.jar org.h2.tools.Server -tcpAllowOthers -pgAllowOthers

2. Add h2*.jar to Payara's classpath

3. Go to admin UI JDBC Connection Pools http://localhost:4848/jdbc/jdbcConnectionPools.jsf
<img width="734" alt="screen shot 2017-11-11 at 10 28 21 pm" src="https://user-images.githubusercontent.com/5786736/32693257-8f01ce42-c730-11e7-8c09-d0d5f7bb5d0f.png">

4. Click New. Choose javax.sql.XADataSource as resource type, enter org.h2.jdbcx.JdbcDataSource as satabase driver vendor.

5. Click Next.
6. Fill the connection details and click Finish
<img width="1181" alt="screen shot 2017-11-11 at 10 34 01 pm" src="https://user-images.githubusercontent.com/5786736/32693279-f67a93d8-c730-11e7-8ca4-fea28e32002e.png">

## Environment ##
- **Payara Version**: 4.1.2.173 (payara 5 alpha 2)
- **Edition**: Full
- **JDK Version**:  8 u144 - Oracle 
- **Operating System**: Mac

**Comment by smillidge** [comment]
Thanks for the detailed bug report. This is a known issue with Payara 5 alpha 3 the tracking ID is PAYARA-2259

**Comment by sfeigl** [comment]
Creating a JNDI custom resource (not JDBC) and adding properties there results in "An error occured" too. 

Is this the same error or should I create a seperate bug report.

**Comment by Cousjava** [comment]
@sfeigl That is a separate known issue that is fixed by #2333

**Comment by afrunt** [comment]
@Cousjava actually, it is not completely fixed. You can reproduce similar issue if you try this guide with 5 Beta 2. Now you can create the pool, but with exceptions and unexpected error messages

https://blog.payara.fish/using-postgresql-with-payara-server

**Comment by smillidge** [comment]
what error messages do you get now?
