### ISSUE TITLE
Healthcheck Events are logged even if the calculated value is below the Good threshold

### ISSUE THREAD

**Issue by skonx** [payara/Payara#2529]
# Description #
----------

Healthcheck events are logged even if the calculated value is below the Good threshold.

## Expected Outcome

events should not be logged.

## Current Outcome

events are logged every 30 seconds.

## Steps to reproduce (Only for bug reports) 

asadmin healthcheck-configure-service --serviceName=healthcheck-cpu --enabled=true --dynamic=true --time=30 --unit=SECONDS

asadmin healthcheck-configure-service-threshold --serviceName=healthcheck-cpu --dynamic=true --thresholdCritical=90 --thresholdWarning=80 --thresholdgood=50

asadmin healthcheck-configure --enabled=true --dynamic=true

=> events are logged even the value is .00 or far below from Good Threshold

> [2018-03-14T18:46:35.161+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.healthcheck.HealthCheckService] [tid: _ThreadID=42 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1521049595161] [levelValue: 800] [[
  Payara Health Check Service Started.]]

> [2018-03-14T18:46:35.163+0100] [Payara 4.1] [SEVERE] [] [fish.payara.nucleus.notification.log.LogNotifierService] [tid: _ThreadID=187 _ThreadName=healthcheck-service-4] [timeMillis: 1521049595163] [levelValue: 1000] [[
>   Health Check notification with severity level: SEVERE - CPUC:Health Check Result:[[status=CRITICAL, message='CPU%: 101.53, Time CPU used: 7 milliseconds'']']]]
> 
> [2018-03-14T18:47:05.169+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.notification.log.LogNotifierService] [tid: _ThreadID=187 _ThreadName=healthcheck-service-4] [timeMillis: 1521049625169] [levelValue: 800] [[
>   Health Check notification with severity level: INFO - CPUC:Health Check Result:[[status=FINE, message='CPU%: .25, Time CPU used: 75 milliseconds'']']]]
> 
> [2018-03-14T18:47:35.166+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.notification.log.LogNotifierService] [tid: _ThreadID=187 _ThreadName=healthcheck-service-4] [timeMillis: 1521049655166] [levelValue: 800] [[
>   Health Check notification with severity level: INFO - CPUC:Health Check Result:[[status=FINE, message='CPU%: .18, Time CPU used: 54 milliseconds'']']]]
> 
> [2018-03-14T18:48:05.168+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.notification.log.LogNotifierService] [tid: _ThreadID=187 _ThreadName=healthcheck-service-4] [timeMillis: 1521049685168] [levelValue: 800] [[
>   Health Check notification with severity level: INFO - CPUC:Health Check Result:[[status=FINE, message='CPU%: .18, Time CPU used: 54 milliseconds'']']]]
> 
> [2018-03-14T18:48:35.167+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.notification.log.LogNotifierService] [tid: _ThreadID=187 _ThreadName=healthcheck-service-4] [timeMillis: 1521049715167] [levelValue: 800] [[
>   Health Check notification with severity level: INFO - CPUC:Health Check Result:[[status=FINE, message='CPU%: .18, Time CPU used: 53 milliseconds'']']]]
> 
> [2018-03-14T18:49:05.171+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.notification.log.LogNotifierService] [tid: _ThreadID=187 _ThreadName=healthcheck-service-4] [timeMillis: 1521049745171] [levelValue: 800] [[
>   Health Check notification with severity level: INFO - CPUC:Health Check Result:[[status=FINE, message='CPU%: .23, Time CPU used: 68 milliseconds'']']]]
> 
> [2018-03-14T18:49:35.168+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.notification.log.LogNotifierService] [tid: _ThreadID=187 _ThreadName=healthcheck-service-4] [timeMillis: 1521049775168] [levelValue: 800] [[
>   Health Check notification with severity level: INFO - CPUC:Health Check Result:[[status=FINE, message='CPU%: .18, Time CPU used: 54 milliseconds'']']]]
> 
> [2018-03-14T18:50:05.172+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.notification.log.LogNotifierService] [tid: _ThreadID=187 _ThreadName=healthcheck-service-4] [timeMillis: 1521049805172] [levelValue: 800] [[
>   Health Check notification with severity level: INFO - CPUC:Health Check Result:[[status=FINE, message='CPU%: 2.15, Time CPU used: 646 milliseconds'']']]]
> 
> [2018-03-14T18:50:35.173+0100] [Payara 4.1] [INFO] [] [fish.payara.nucleus.notification.log.LogNotifierService] [tid: _ThreadID=187 _ThreadName=healthcheck-service-4] [timeMillis: 1521049835173] [levelValue: 800] [[
>   Health Check notification with severity level: INFO - CPUC:Health Check Result:[[status=FINE, message='CPU%: 1.94, Time CPU used: 582 milliseconds'']']]]

## Context (Optional)

same behavior using local log file or slack.

## Environment ##

- **Payara Version**: Payara Server  4.1.2.174 #badassfish (build 192)
- **Edition**: Full
- **JDK Version**: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
- **Operating System**: MAC OS 10.13.3

**Comment by smillidge** [comment]
This is more a feature than a bug. I will therefore label this as an enhancement request.

**Comment by smillidge** [comment]
Fixed in 5.183

**Comment by skonx** [comment]
Hi @smillidge  
BTW, it's still present in the 5.191.

Between 0 and Good Threshold, it logs with FINE:
`payara-server : Health Check notification with severity level: FINE. (host:79860a35d717, server:server, domain:production,instance:server)
CPUC:Health Check Result:[[status=FINE, message='CPU%: 1.75, Time CPU used: 526 milliseconds'']']`

**Comment by skonx** [comment]
All my apologizes @smillidge.
I've just found this https://github.com/payara/Payara-Server-Documentation/blob/master/documentation/payara-server/health-check-service/asadmin-commands.adoc#healthcheck-configure-service

**Comment by skonx** [comment]
So, many things changed. 
Could you please provide advises? 
I'm lost with these different settings.
