### ISSUE TITLE
The Health Check API endpoint isn't reliable

### ISSUE THREAD

**Issue by tofflos** [payara/Payara#2595]
# Description #

The Health Check API endpoint is launched when application deployment begins and will report that the application is ready to receive requests before deployment has been completed.

If the endpoint receives a request before it has been started then Payara will respond with a plain text response and status code 404.

If deployment fails the endpoint will stay operational and continue to report that the application is ready to receive requests. 

If an application registers custom health checks then these will report that the application is ready to receive requests before any JAX-RS resources become operational.

If an application registers custom health checks and deployment fails then further requests to the endpoint will result in an internal server error.

## Expected Outcome

Honestly I'm not sure.

One option could be to delay launching the endpoint until the application has been successfully deployed. This would hopefully eliminate all the intermediate states. I've explored this possibility for a while in the [HealthCheckService](https://github.com/payara/Payara/blob/a2745de9830efdda7bebdf94d29b443f5b1e6576/appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java) by listening for a Deployment.DEPLOYMENT_SUCCESS event but was unable to come up with the ServletContext reference needed to invoke addServlet.

Another option could be launching the endpoint on server start and have it respond that the application is DOWN until deployment has been successfully completed. But this could be a violation of the specification "A producer without health check procedures installed MUST returns positive overall outcome (i.e. HTTP 200)". See https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/protocol-wireformat.adoc.

## Environment ##

- **Payara Version**: 5.181
- **Edition**: Micro
- **JDK Version**: 8 u162 - Oracle
- **Operating System**: Windows

**Comment by tofflos** [comment]
Minimal project that reproduces the behavior:
[mavenproject73.zip](https://github.com/payara/Payara/files/1873039/mavenproject73.zip)

**Comment by tofflos** [comment]
Creating the minimal project was a bit painful because the problem is timing related. It contains six tests of which four are failing. I was unable to reproduce the fifth case. The sixth case is a successful reference case that you can compare against.

| Test | Outcome |
| ---- | --------- |
| applicationShouldBeOperationalAfterSuccessfulHealthCheck | Failure |
| applicationShouldBeOperationalAfterSuccessfulCustomHealthCheck | Success |
| doGet (Reference case) | Success |
| endpointShouldNotBeBrokenAfterUnsuccessfulDeployment | Failure
| endpointShouldNotBeBrokenAfterUnsuccessfulDeploymentWithCustomHealthCheck | Failure |
| endpointShouldConformToProtocolAndWireformat | Failure |

**Comment by OndrejM** [comment]
Part of this issue is that MicroProfile Health doesn't cover the startup/deployment period. If only declares how to report the status once the service is running. What you expect is a "readiness" check to find out when your application is fully started and ready to process requests.

"readiness" checks as a complement to the current health checks are being discussed here: https://github.com/eclipse/microprofile-health/issues/35. So, hopefully, this will be addressed in the future MicroProfile Health version and subsequently in Payara.

**Comment by OndrejM** [comment]
So what stays is that the Health endpoint in Payara isn't reliable if application deployment fails:

* If deployment fails the endpoint will stay operational and continue to report that the application is ready to receive requests.
* If an application registers custom health checks and deployment fails then further requests to the endpoint will result in an internal server error.

What's the expected behavior here? I assume that:

* if deployment fails, the health check service reports 503 until the next successful deployment (of any application, not necessarily the same application, because maybe that app wouldn't be deployed anymore and there would be no way to restore an OK state). Alternatively, an error would be reported until an OK status is established by a server admin

* If an application registers custom health checks and deployment fails then all custom health checks are properly unregistered. This would still lead into 503 as per the above point but would avoid calling custom healthchecks and would allow that an OK state is restored after a successful redeployment.

**Comment by smillidge** [comment]
Fixed in 5.191. Healthcheck is marked as DOWN unless an application is successfully deployed.

**Comment by jbee** [comment]
Apparently this issue is not fixed and needs reopening. I encountered it on master. Created internal issue CUSTCOM-300 to track it.
