### ISSUE TITLE
using javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL causes viewParam to be null /CUSTCOM-110

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [payara/Payara#3849]
# Description #
using javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL causes viewParam previous filled values to be null after primefaces ajax with jsf 2.3. mojarra 2.2 was working. I opened PrimeFaces issue, but they told me this is Mojarra 2.3 bug.

## Expected Outcome
value filled within URL should remain in bean

## Current Outcome
value is nulled

## Steps to reproduce (Only for bug reports) 
access URL https://YOUR_LOCAL_HOST_COME_HERE/JSF23WebSocket-1.0/?test=bah
check the log: the url value is there
come back to the page and click the button
the value in bean is nulled

### Samples

https://github.com/erickdeoliveiraleal/test_jsf23_update

## Environment ##

- **Payara Version**: 5.1.191
- **Edition**: full
- **JDK Version**: Oracle 8
- **Operating System**: Windows 10
- **Database**: none

**Comment by smillidge** [comment]
Thanks for the test case we will try to reproduce the issue

**Comment by rdebusscher** [comment]
Hi,

I have reduced your test example (removed Primefaces, WebSocket, endorsed directory usage etc) and can reproduce the problem when the AJAX request is executed the second time from the <h:commandButton>.

I have created `CUSTCOM-110`.

**Comment by erickdeoliveiraleal** [comment]
Fixed in mojarra https://github.com/eclipse-ee4j/mojarra/pull/4643

**Comment by sgflt** [comment]
Is the fix present in master or Mojarra is broken again? I have tested it against 5.2020.3 and the problem is still there.

`[2020-07-31T12:43:13.727+0200] [Payara 5.2020.3] [INFO] [] [] [tid: _ThreadID=105 _ThreadName=http-thread-pool::http-listener-1(1)] [timeMillis: 1596192193727] [levelValue: 800] [[
  initializing: bah]]

[2020-07-31T12:43:16.679+0200] [Payara 5.2020.3] [INFO] [] [] [tid: _ThreadID=109 _ThreadName=http-thread-pool::http-listener-1(5)] [timeMillis: 1596192196679] [levelValue: 800] [[
  bah]]

[2020-07-31T12:43:17.408+0200] [Payara 5.2020.3] [INFO] [] [] [tid: _ThreadID=105 _ThreadName=http-thread-pool::http-listener-1(1)] [timeMillis: 1596192197408] [levelValue: 800] [[
  null]]
`

**Comment by dmatej** [comment]
@sgflt The internal issue FISH-77 is still not closed, we have to upgrade Mojarra first, but the commit with the fix is not yet in any released Mojarra yet.

**Comment by sgflt** [comment]
https://github.com/eclipse-ee4j/mojarra/issues/4714
