### ISSUE TITLE
Bug Report: CDI tries to instantiate interface (Payara Community 5.2021.2)

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#5208]
# Description #
----------

An interface annotated by `@Path` found in a WAR file results in a warning that CDI cannot instantiate it. 

## Expected Outcome ##

No instance is created, and no warning is found in the log file.

## Current Outcome ##

No instance is created, but a warning is found in the log file:
```
[2021-04-22T16:41:02.890+0200] [Payara 5.2021.2] [WARNING] [] [org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider] [tid: _ThreadID=103 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1619102462890] [levelValue: 900] [[
  Component of class interface mypackage.MyInterface cannot be instantiated and will be ignored.]]
```
## Steps to reproduce ## 

Deploy a WAR file containing an interface annotated by `@Path("")`, then send a request against the base URL of the WAR file.

## Environment ##

- **Distribution**: Payara Full Server Community Edition 5.2021.2
- **JDK Version**: Java 8 (Azul Zulu)
- **Operating System**: Windows 10 (64 Bit)

# Notes # 

Originally reported against [Payara](https://github.com/payara/Payara/issues/5208), but I assume it is a [Jersey](https://github.com/eclipse-ee4j/jersey/issues/4781) bug.

**Comment by oldpirate** [comment]
hi,
seems fixed with the version 5.2021.4

**Comment by shub8968** [comment]
HI @mkarg,

Would you be able to verify it on version 5.2021.4

**Comment by mkarg** [comment]
@OndroMih Can you please reopen this bug report? I can still reproduce it with Payara 5.2021.8 as there is no Jersey 2.x published yet which actually fixes this problem. The solution is announced for upcoming Jersey 2.36, see here: https://github.com/eclipse-ee4j/jersey/pull/4847. Thanks.

**Comment by OndroMih** [comment]
Hi @mkarg , I reopened this issue but we'll need to wait for the Jersey 2.36 release before we can upgrade Jersey in Payara Server to fix this. Please notify us here when Jersey 2.36 is released in case we miss that.

**Comment by JamesHillyard** [comment]
Payara Server 5.2022.2 has been upgraded to Jersey 2.36. You shouldn't encounter this issue now in the latest version of Payara Community.

Thanks,
James
