### ISSUE TITLE
asadmin fails on add-resources when creating a jdbc pool with connection validation

### ISSUE THREAD

**Issue by jesper-bruun** [payara/Payara#914]
The xml resource file looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Resource Definitions//EN" "http://glassfish.org/dtds/glassfish-resources_1_5.dtd">
<resources>
  <jdbc-connection-pool validate-atmost-once-period-in-seconds="10" datasource-classname="org.postgresql.xa.PGXADataSource" name="mytestpool" validation-classname="org.glassfish.api.jdbc.validation.PostgresConnectionValidation" is-connection-validation-required="true" connection-validation-method="custom-validation" res-type="javax.sql.XADataSource">
      <property name="user" value="harv"></property>
      <property name="PortNumber" value="5432"></property>
      <property name="password" value="harv"></property>
      <property name="DriverClass" value="org.postgresql.Driver"></property>
      <property name="DatabaseName" value="harv_db"></property>
      <property name="serverName" value="localhost"></property>
    </jdbc-connection-pool>
</resources>
```

When I try to run it using

`./payara41/bin/asadmin add-resources ./res.xml`

I get: 
`JDBC connection pool mytestpool creation failed. Constraints for this JdbcConnectionPool configuration have been violated: on property [  ] violation reason [ Must specify 'validation-class-name' when 'connection-validation' is enabled and 'validation-method' is 'custom-validation'. Please specify 'validation-class-name' before enabling 'custom-validation' based validation. ]`

Nevertheless it can easily be done using the web-admin console. In fact I copied `jdbc-connection-pool` section from `domain.xml` when I did the xml.

**Comment by mikecroft** [comment]
You have set the attribute for your validation class name slightly incorrectly in the parent `<jdbc-connection-pool>` element:

You have:
`validation-classname` not:
`validation-class-name`.

Add the extra hyphen in and it should work.

**Comment by jesper-bruun** [comment]
Hmm tried that. I get:

remote failure: add-resources <res.xml> failed
Attribute "validation-class-name" must be declared for element type "jdbc-connection-pool".
Command add-resources failed.

**Comment by mikecroft** [comment]
Yes, looking at the DTD, your original XML file is correct and the error message is wrong.

I've created internal defect `PAYARA-904` for the issue. I used your XML file here with the `add-resources` command and got the same result with the latest build.

I also created `PAYARA-903` to track the incorrect error message

**Comment by jesper-bruun** [comment]
OK thanx

**Comment by MeroRai** [comment]
@jesper-bruun Problems seems to be when it is parsing through a file, it doesn't correctly parse `validation-classname`. Fix is available at https://github.com/payara/Payara/pull/935.

**Comment by smillidge** [comment]
Fixed by #935 and #925

**Comment by danilomagrini** [comment]
I am using Payara 4.1.1.163 and this error persist.

```
Grave:   Exception while deploying the app [MyApp]
Grave:   Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: Failue while processing glassfish-resources.xml(s) in the archive  -- O atributo "validation-class-name" deve ser declarado para o tipo de elemento "jdbc-connection-pool".
	at org.glassfish.resources.admin.cli.ResourcesXMLParser.initProperties(ResourcesXMLParser.java:277)
	at org.glassfish.resources.admin.cli.ResourcesXMLParser.<init>(ResourcesXMLParser.java:151)
	at org.glassfish.resources.module.ResourcesDeployer.processArchive(ResourcesDeployer.java:274)
	at org.glassfish.resources.module.ResourcesDeployer.processResources(ResourcesDeployer.java:766)
	at org.glassfish.resources.module.ResourcesDeployer.event(ResourcesDeployer.java:715)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:420)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)

Grave:   Exception while deploying the app [MyApp] : Failue while processing glassfish-resources.xml(s) in the archive  -- O atributo "validation-class-name" deve ser declarado para o tipo de elemento "jdbc-connection-pool".
```

glassfish-resources.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Resource Definitions//EN" "http://glassfish.org/dtds/glassfish-resources_1_5.dtd">
<resources>
    <jdbc-connection-pool allow-non-component-callers="false" 
                          associate-with-thread="false" 
                          connection-creation-retry-attempts="0" 
                          connection-creation-retry-interval-in-seconds="10" 
                          connection-leak-reclaim="false" 
                          connection-leak-timeout-in-seconds="0" 
                          validation-class-name="org.glassfish.api.jdbc.validation.MySQLConnectionValidation"
                          connection-validation-method="custom-validation" 
                          datasource-classname="com.mysql.jdbc.jdbc2.optional.MysqlXADataSource" 
                          fail-all-connections="false" 
                          idle-timeout-in-seconds="300" 
                          is-connection-validation-required="true" 
                          is-isolation-level-guaranteed="true" 
                          lazy-connection-association="false" 
                          lazy-connection-enlistment="false" 
                          match-connections="false" 
                          max-connection-usage-count="0" 
                          max-pool-size="32" 
                          max-wait-time-in-millis="60000" 
                          name="mmlPool" 
                          non-transactional-connections="false" 
                          pool-resize-quantity="2" 
                          res-type="javax.sql.XADataSource" 
                          statement-timeout-in-seconds="-1" 
                          steady-pool-size="8" 
                          validate-atmost-once-period-in-seconds="60" 
                          wrap-jdbc-objects="true">
        <property name="URL" value="jdbc:mysql://localhost:3306/dbmml?zeroDateTimeBehavior=convertToNull"/>
        <property name="User" value="root"/>
        <property name="Password" value="root"/>
    </jdbc-connection-pool>
    <jdbc-resource enabled="true" jndi-name="jdbc/mml" object-type="user" pool-name="mmlPool">
        <description/>
    </jdbc-resource>
</resources>
```

**Comment by smillidge** [comment]
Try validation-classname not validation-class-name
